<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="CommandHandlers\" />
    <Folder Include="CommandDecorators\" />
    <Folder Include="Mapper\" />
    <Folder Include="QueryHandlers\" />
    <Folder Include="Services\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Api.Common\1.Api.Common.csproj" />
    <ProjectReference Include="..\Api.Contract\2.Api.Contract.csproj" />
    <ProjectReference Include="..\Api.DAL\3.Api.DAL.csproj" />
  </ItemGroup>

</Project>
